// src/components/sections/Billing.vue
<template>
  <section class="section section--billing">
    <div class="container container--large">
      <header class="section-header">
        <h2 class="section__title">Predictable &amp; Transparent Billing</h2>
        <a href="#0" class="btn btn--outlined">Detailed Pricing</a>
      </header>
      <div class="section-content">
        <div class="identification-per-month">
          <h3 class="identification-per-month__title">Select your identifications per month</h3>
          <div class="slider" ref="slider">
            <span class="slider-output" v-text="valueLabel"></span>
            <label for="billingSlider" class="slider-label">
              <span class="slider-label__text">100K</span>
              <span class="slider-label__text">250K</span>
              <span class="slider-label__text">500K</span>
              <span class="slider-label__text">1M</span>
              <span class="slider-label__text">5M</span>
              <span class="slider-label__text">10M</span>
              <span class="slider-label__text">20M</span>
            </label>
            <div class="slider-input-container">
              <input
                class="slider-input"
                type="range"
                min="0"
                max="6"
                name="billing-slider"
                value="3"
                @change="handleChange"
              />
            </div>
          </div>
          <p class="identification-per-month__footnote">
            Our standard plan comes with 1 year visit history and email support.
            <br />Contact sales for enterprise support license and secure unlimited visit history and 24/7 dedicated support.
          </p>
        </div>
        <div class="payment">
          <div class="payment-per-month">
            <span class="price" v-text="priceLabel"></span>
            per month
          </div>
          <div class="billed">billied yearly</div>
          <div class="payment-switcher">
            <button
              class="payment-switcher__button payment-switcher__button--annually"
              :class="{
                'payment-switcher__button--active': billingType === 'annually',
              }"
              @click="updateBilling('annually')"
            >Pay Annually</button>
            <button
              class="payment-switcher__button payment-switcher__button--monthly"
              :class="{
                'payment-switcher__button--active': billingType === 'monthly',
              }"
              @click="updateBilling('monthly')"
            >Pay Monthly</button>
          </div>
          <p class="payment__description">
            You get annual payment benefits Switch to annual to get
            <strong>20% Discount roll-over</strong> of unused monthly API calls
          </p>
        </div>
      </div>
      <div class="section-link">
        <a href="#0" class="btn btn--outlined">Detailed Pricing</a>
      </div>
    </div>
  </section>
</template>

<script lang="ts">
import Vue from "vue"

export default Vue.extend({
  name: "Billing",
  props: {},
  data() {
    return {
      billingType: "annually",
      pricingTable: [
        { label: "100K", value: 100000 },
        { label: "250K", value: 250000 },
        { label: "500K", value: 500000 },
        { label: "1M", value: 1000000 },
        { label: "5M", value: 5000000 },
        { label: "10M", value: 10000000 },
        { label: "20M", value: 20000000 },
      ],
      valueLabel: "1M",
      priceLabel: "$800",
    }
  },
  methods: {
    handleChange: function(e: Event) {
      const elem = e.target as HTMLInputElement
      const minValue = Number(elem.min)
      const maxValue = Number(elem.max)
      const value = Number(elem.value)
      const magicNumber = ((value - minValue) * 100) / (maxValue - minValue)
      this.valueLabel = this.pricingTable[value].label
      this.priceLabel = this.calculatePrice(this.pricingTable[value].value)

      this.slider.style.setProperty(
        "--left",
        `calc(${magicNumber}% + (${15 - magicNumber * 0.3}px))`
      )
    },
    calculatePrice: function(price: number) {
      const currencyFormatOptions = {
        maximumSignificantDigits: 3,
        style: "currency",
        currencyDisplay: "symbol",
        currency: "USD",
        notation: "standard",
      }

      if (this.billingType === "monthly") {
        return new Intl.NumberFormat("en-US", currencyFormatOptions).format(
          price / 1000
        )
      }
      if (this.billingType === "annually") {
        return new Intl.NumberFormat("en-US", currencyFormatOptions).format(
          (price / 1000) * 0.8
        )
      }
      return ""
    },
    updateBilling: function(type: string) {
      this.billingType = type
    },
  },
  computed: {
    slider(): HTMLElement {
      return this.$refs.slider as HTMLElement
    },
  },
})
</script>

// src/components/Billing/index.tsx
import React, { useState, useEffect } from 'react'
import { Link } from 'gatsby'
import classNames from 'classnames'
import { PaymentType } from '../../types/PaymentType'
import { handlePriceChange } from '../../utils/pricing'
import Container from '../base/Container'

const sliderConfig = {
  min: 0,
  max: 6,
  default: 0,
}

export default function Billing() {
  const [paymentType, setPaymentType] = useState<PaymentType>(PaymentType.monthly)
  const [sliderValue, setSliderValue] = useState(sliderConfig.default)

  const [valueLabel, setValueLabel] = useState('')
  const [monthlyPayment, setMonthlyPayment] = useState('')
  const [sliderOffsetCss, setSliderOffsetCss] = useState('')

  const handleSliderChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    const newValue = Number(e.target.value)
    setSliderValue(newValue)
    recalculatePricing(newValue, paymentType)
  }

  const handlePaymentTypeChange = (type: PaymentType) => () => {
    setPaymentType(type)
    recalculatePricing(sliderValue, type)
  }

  const recalculatePricing = (sliderValue: number, paymentType: PaymentType) => {
    const { valueLabel, newPrice, leftOffsetCss } = handlePriceChange(
      sliderConfig.min,
      sliderConfig.max,
      sliderValue,
      paymentType
    )
    setValueLabel(valueLabel)
    setMonthlyPayment(newPrice)
    setSliderOffsetCss(leftOffsetCss)
  }

  useEffect(() => {
    recalculatePricing(sliderValue, paymentType)
  }, [])

  return (
    <section className='section section--billing'>
      <Container size='large'>
        <header className='section-header'>
          <h2 className='section__title'>Predictable &amp; Transparent Billing</h2>
          <Link to='/pricing' className='btn btn--outlined'>
            Detailed Pricing
          </Link>
        </header>
        <div className='section-content'>
          <div className='identification-per-month'>
            <h3 className='identification-per-month__title'>
              How many identification API calls per month do you need?
            </h3>
            <div className='slider' style={{ '--left': sliderOffsetCss } as React.CSSProperties}>
              <span className='slider-output'>{valueLabel}</span>
              <label htmlFor='billingSlider' className='slider-label'>
                <span className='slider-label__text'>100K</span>
                <span className='slider-label__text'>250K</span>
                <span className='slider-label__text'>500K</span>
                <span className='slider-label__text'>1M</span>
                <span className='slider-label__text'>5M</span>
                <span className='slider-label__text'>10M</span>
                <span className='slider-label__text'>20M</span>
              </label>
              <div className='slider-input-container'>
                <input
                  className='slider-input'
                  type='range'
                  min={sliderConfig.min}
                  max={sliderConfig.max}
                  value={sliderValue}
                  name='billing-slider'
                  onChange={handleSliderChange}
                />
              </div>
            </div>
            <p className='identification-per-month__footnote'>
              Our standard plan comes with 1 year visit history and email support.
              <br />
              <br />
              <a href='mailto:sales@fingerprintjs.com' style={{ textDecoration: 'underline' }}>
                Contact sales
              </a>
              for an enterprise license, 99.9% SLA and 24/7 dedicated support.
            </p>
          </div>
          <div className='payment'>
            <div className='payment-per-month'>
              <span className='price'>{monthlyPayment}</span>
              per month
            </div>
            <div className='billed' id='billed_annual_text'>
              billed yearly
            </div>
            <div className='payment-switcher' data-type='annually'>
              <button
                className={classNames('payment-switcher__button', 'payment-switcher__button--annually', {
                  'payment-switcher__button--active': paymentType === PaymentType.annually,
                })}
                onClick={handlePaymentTypeChange(PaymentType.annually)}
                data-type='annually'
              >
                Pay Annually
              </button>
              <button
                className={classNames('payment-switcher__button', 'payment-switcher__button--monthly', {
                  'payment-switcher__button--active': paymentType === PaymentType.monthly,
                })}
                onClick={handlePaymentTypeChange(PaymentType.monthly)}
                data-type='monthly'
              >
                Pay Monthly
              </button>
            </div>
            <p className='payment__description'>
              With annual pricing you lock in an annual price with a discount by prepaying. This plan is recommended for
              users with predictable or high traffic volumes.
            </p>
          </div>
        </div>
        <div className='section-link'>
          <a href='#0' className='btn btn--outlined'>
            Detailed Pricing
          </a>
        </div>
      </Container>
    </section>
  )
}
