// src/components/Header.tsx
import React, {useEffect} from 'react'
import Navbar from './Navbar'
import { Link } from 'gatsby'
import '../css/index.scss'

import Prism from "prismjs";
import 'prismjs/plugins/line-numbers/prism-line-numbers';
// import logo from '../img/company-logos/fpjs.svg'

export default function Header() {
    useEffect(() => {
        Prism.highlightAll();
    }, []);

    return (
        <>
            <Navbar/>
            <div className="main-nav">
                <div className="container container--large">
                    <nav className="nav nav--main">
                        <div className="nav-left">
                        <Link to="/" className="nav__link nav__link--logo" title="Logo">
                            <img src="/img/company-logos/fpjs.svg" alt="FingerprintJS" className='nav__logo' />
                        </Link>
                        </div>
                        <div className="nav-right">
                        <a className="btn btn--github" href="https://github.com/fingerprintjs/fingerprintjs">
                            <div className="btn__label">
                            <svg className="icon">
                                {/* <use xlink:href="#github"></use> */}
                            </svg>
                            <span>
                                Star
                            </span>
                            </div>
                            <div className="github-counter">12,001</div>
                        </a>          
                        <a href="mailto:sales@fingerprintjs.com" className="btn btn--outlined">
                            Contact Sales
                        </a>
                        <a href="https://dashboard.fingerprintjs.com/signup" className="btn">
                            Free Trial
                        </a>
                        <button className="btn btn--clear btn--icon-only mobile-toggler">
                            <svg className="btn__icon">
                            {/* <use xlink:href="#burger"></use> */}
                            </svg>
                        </button>
                        </div>
                    </nav>
                </div>       
            </div>
        </>
    )
}

// src/components/Header.vue
<template>
  <header class="header">
    <div class="top-nav">
      <div class="container container--large">
        <nav class="nav nav--secondary">
          <a href="#0" class="nav__link">(844) 4FJS</a>
          <a href="#0" class="nav__link">Support</a>
          <a href="#0" class="nav__link">Log In/Sign Up</a>
        </nav>
      </div>
    </div>
    <div class="main-nav">
      <div class="container container--large">
        <nav class="nav nav--main">
          <div class="nav-left">
            <a href="#0" class="nav__link nav__link--logo">FingerPrintJS</a>
            <a href="#0" class="nav__link">Docs </a>
            <a href="#0" class="nav__link">Pricing</a>
          </div>
          <div class="nav-right">
            <a
              class="github-button"
              href="https://github.com/fingerprintjs/fingerprintjs2"
              data-icon="octicon"
              data-size="large"
              data-show-count="true"
              aria-label="Star fingerprintjs/fingerprintjs2 on GitHub"
              >Star</a
            >
            <a href="#0" class="btn btn--outlined">Contact Sales</a>
            <a href="#0" class="btn" v-bind:class="{ hidden: isMobileMenuOpen }"
              >Free Trial</a
            >
            <button
              class="btn btn--clear btn--icon-only mobile-toggler"
              @click="toggleMobileMenu"
            >
              <svg class="btn__icon">
                <use xlink:href="#burger"></use>
              </svg>
            </button>
          </div>
        </nav>
      </div>
    </div>
    <div
      class="mobile-nav"
      v-bind:class="{ 'mobile-nav--open': isMobileMenuOpen }"
    >
      <div class="container container--large">
        <div class="top-links">
          <a href="#0" class="btn btn--outlined">Contact Sales</a>
          <a href="#0" class="btn">Free Trial</a>
        </div>
        <div class="main-links">
          <a href="#0" class="main-links__link">Docs</a>
          <a href="#0" class="main-links__link">Pricing</a>
        </div>
        <div class="contact-social">
          <a
            class="github-button"
            href="https://github.com/fingerprintjs/fingerprintjs2"
            data-icon="octicon"
            data-size="large"
            data-show-count="true"
            aria-label="Star fingerprintjs/fingerprintjs2 on GitHub"
            >Star</a
          >
          <div class="social">
            <small>Find us on social</small>
            <ul class="social-links">
              <li class="social-links__link">
                <a href="#0">
                  <svg>
                    <use xlink:href="#linkedin"></use>
                  </svg>
                </a>
              </li>
              <li class="social-links__link">
                <a href="#0">
                  <svg>
                    <use xlink:href="#twitter"></use>
                  </svg>
                </a>
              </li>
              <li class="social-links__link">
                <a href="#0">
                  <svg>
                    <use xlink:href="#medium"></use>
                  </svg>
                </a>
              </li>
            </ul>
          </div>
        </div>
      </div>
      <div class="secondary-links">
        <div class="container container--large">
          <a href="#0" class="nav__link">(844) 4FJS</a>
          <a href="#0" class="nav__link">Support</a>
          <a href="#0" class="nav__link">Log In/Sign Up</a>
        </div>
      </div>
    </div>
  </header>
</template>

<script lang="ts">
import Vue from "vue"

export default Vue.extend({
  name: "Header",
  props: {},
  data() {
    return { isMobileMenuOpen: false }
  },
  methods: {
    toggleMobileMenu: function() {
      console.log(document.body)
      this.isMobileMenuOpen = !this.isMobileMenuOpen
      document.body.classList.toggle("noscroll")
    },
    handleWindowResize: function() {
      if (!window.matchMedia("(max-width: 1024px)").matches) {
        document.body.classList.remove("noscroll")
        this.isMobileMenuOpen = false
      }
    },
  },
  created() {
    window.addEventListener("resize", this.handleWindowResize)
  },
  destroyed() {
    window.removeEventListener("resize", this.handleWindowResize)
  },
})
</script>
